spring.application.name=auth-service
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
server.port=9001

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
logging.level.org.springframework.security=DEBUG
logging.level.com.julia.authservice.feingclients=DEBUG